### PR TITLE
Write image data more times if FWU MAX BLOCK SIZE is not big enough

### PR DESCRIPTION
**Pull request by xinyu-tfm**
Chances are that ulBlockSize is bigger than PSA_FWU_MAX_BLOCK_SIZE.
It is needed to call psa_fwu_write for more times to make sure all
data in the block are completely written in this case.

Signed-off-by: Xinyu Zhang <xinyu.zhang@arm.com>
Change-Id: I504080d7144e7542ce81bbca457568b91606e745

### CODE REVIEW

**Comment by Sherryzhang2** [comment]
This PR has been verified with the AWS OTA server.

**Review by Sherryzhang2 — APPROVED** [review]
This PR looks good to me.

**Review by microbuilder — APPROVED** [review]

**Review by pfalcon — COMMENTED** [review]
The implementation of the feature stated in the change subject ("Write image data more times if FWU MAX BLOCK SIZE is not big enough") looks fine. However I would point out the the commit contains changes not related to this functionality. I.e. changes to README.md and ota_pal.h don't seem to be related in any way to "Write image data more times if FWU MAX BLOCK SIZE is not big enough". Under some of other projects' change policies, such unrelated changes would need to go into their own commits with commit messages properly decsribing them. But I don't know what is the change policies of this project, maybe it's ok here.

Given that this PR already has 2 approvals (which should be enough for merging), let me just add this as a comment (i.e. +0).

**Comment by xinyu-tfm** [comment]
Hi @pfalcon , many thanks for your comment!
I have split this PR into two commit -- one for updating write logic and one for updating README & Copyright.

**Review by pfalcon — APPROVED** [review]
Thanks for the update, looks great. Given that no other concerns/suggestion were sounded, merging.

**Pull request merged**
